# -*- coding: utf-8 -*-
"""
Snowflake concept data for the PJ's Academy Instagram infographic PDF.
Same rich schema as the Python Data Science infographics.
12 concepts across 5 phases (blue Snowflake palette).
"""

CONCEPTS = [
    {
        "num": "01", "phase": "Phase 1 · Foundations",
        "title": "What is\nSnowflake?",
        "description": "Snowflake is a fully-managed cloud data platform that separates storage from compute — so you can store unlimited data cheaply and scale compute independently, paying only per second of use.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "No servers to manage — Snowflake runs it all for you",
            "Storage & compute scale separately — no contention, no waste",
            "Pay-per-second billing — spin up, run, suspend, save money",
            "One platform for warehousing, data lakes, engineering & ML",
        ],
        "types_title": "WHERE IT RUNS",
        "types": [
            ("☁️", "AWS", "Amazon Web Services regions worldwide"),
            ("🔷", "Azure", "Microsoft Azure cloud"),
            ("🌐", "GCP", "Google Cloud Platform"),
        ],
        "quote": "Snowflake isn't a database you install —\nit's a data cloud you simply use.",
        "bp_boxes": ["Your\nData", "Cloud\nStorage", "Virtual\nWarehouse", "Insights"],
        "bp_note": "Data lands in cloud storage; warehouses compute on demand.",
        "at_a_glance": [
            ("🏢", "FOUNDED", "2012"),
            ("📈", "IPO", "2020 (biggest software IPO)"),
            ("💰", "SALARY", "₹18–45 LPA in India"),
        ],
        "real_world": [
            ("🎬", "Netflix", "Analyses viewing data across millions of users"),
            ("🏦", "Capital One", "Runs risk & fraud analytics at scale"),
            ("🛒", "Instacart", "Powers real-time inventory analytics"),
            ("🎮", "EA Games", "Player behaviour & telemetry analysis"),
        ],
        "did_you_know": [
            ("❄️", "The name reflects its founders' love of snow sports."),
            ("⚡", "It can query petabytes without you managing a single server."),
            ("🔄", "Storage and compute scale completely independently."),
        ],
        "how_title": "HOW IT WORKS",
        "how": [
            ("📥", "STORE", "Data lands in\ncloud storage"),
            ("⚙️", "COMPUTE", "Warehouses\nprocess queries"),
            ("🧠", "SERVICE", "Brain layer\noptimises it all"),
        ],
        "ex_title": "THE 3 LAYERS",
        "ex_cards": [
            ("🧠", "SERVICES", "Auth,\noptimiser"),
            ("⚙️", "COMPUTE", "Virtual\nwarehouses"),
            ("💾", "STORAGE", "Micro-\npartitions"),
        ],
        "g1": [
            ("EDITIONS", ["Standard", "Enterprise", "Business Critical", "VPS"]),
            ("INTERFACES", ["Snowsight (UI)", "SnowSQL (CLI)", "Python / Spark", "JDBC / ODBC"]),
        ],
        "g2": [
            ("VS TRADITIONAL", [("✓", "No tuning knobs"), ("✓", "Auto-scaling"), ("✓", "Pay per second")]),
            ("USE CASES", [("📊", "Warehousing"), ("🔧", "Data engineering"), ("🤖", "ML / AI")]),
        ],
        "footer": "Master Snowflake and you master the modern data stack.",
        "quick_ref": [
            ("KEY TERMS", [("Warehouse", "Compute cluster"), ("Micro-partition", "Storage unit")]),
            ("BILLING", [("Credit", "Unit of compute"), ("Per-second", "Billing model")]),
            ("EDITIONS", [("Standard", "Entry tier"), ("Enterprise", "90-day travel")]),
            ("CLOUDS", [("AWS", "Most regions"), ("Azure/GCP", "Also supported")]),
        ],
        "next_up": "Virtual Warehouses",
        "next_desc": "The compute engines that power every query.",
    },
    {
        "num": "02", "phase": "Phase 1 · Foundations",
        "title": "Virtual\nWarehouses",
        "description": "A virtual warehouse is a cluster of compute that runs your queries. Resize it up for heavy jobs, scale it out for many users, and auto-suspend it to stop paying when idle.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Compute is separate from storage — run 10 at once, no conflict",
            "Resize instantly (XS → 6XL) — no downtime, no data reload",
            "Auto-suspend/resume means you pay only while querying",
            "Multi-cluster warehouses handle concurrency spikes automatically",
        ],
        "types_title": "TWO WAYS TO SCALE",
        "types": [
            ("⬆️", "Scale UP", "Bigger warehouse for complex queries"),
            ("➡️", "Scale OUT", "More clusters for more concurrent users"),
            ("⏸️", "Auto-suspend", "Pause when idle to save credits"),
        ],
        "quote": "Bigger isn't always better —\nright-sizing your warehouse is the real skill.",
        "bp_boxes": ["Query", "Warehouse\nspins up", "Runs", "Auto-\nsuspends"],
        "bp_note": "Each size up doubles both compute power and credits/hour.",
        "at_a_glance": [
            ("📏", "SIZES", "XS to 6XL"),
            ("⚡", "SCALING", "Up or Out"),
            ("💤", "SUSPEND", "60s recommended"),
        ],
        "real_world": [
            ("🛍️", "Retail", "Scale out for Black Friday query spikes"),
            ("📊", "BI teams", "Separate warehouse per department"),
            ("🔬", "Data science", "Large warehouse for heavy ML feature jobs"),
            ("🌙", "ETL", "Dedicated warehouse for nightly loads"),
        ],
        "did_you_know": [
            ("💰", "A suspended warehouse costs ₹0 — only storage is billed."),
            ("📐", "Each size step doubles credits: XS=1, S=2, M=4, L=8/hr."),
            ("🔀", "Multi-cluster is an Enterprise-edition feature."),
        ],
        "how_title": "USING WAREHOUSES",
        "how": [
            ("🆕", "CREATE", "Define size\n& auto-suspend"),
            ("▶️", "RUN", "Execute your\nqueries"),
            ("💤", "SUSPEND", "Auto-pause\nwhen idle"),
        ],
        "ex_title": "SIZE → CREDITS/HR",
        "ex_cards": [
            ("🟢", "XS", "1 credit"),
            ("🟡", "MEDIUM", "4 credits"),
            ("🔴", "X-LARGE", "16 credits"),
        ],
        "g1": [
            ("SETTINGS", ["WAREHOUSE_SIZE", "AUTO_SUSPEND", "AUTO_RESUME", "MIN/MAX_CLUSTER"]),
            ("BEST PRACTICE", ["Suspend at 60s", "Start small", "Separate by workload"]),
        ],
        "g2": [
            ("SCALE UP", [("→", "Complex query"), ("→", "Big joins"), ("→", "Resize bigger")]),
            ("SCALE OUT", [("→", "Many users"), ("→", "Concurrency"), ("→", "Add clusters")]),
        ],
        "footer": "Control your warehouses well and you control your bill.",
        "quick_ref": [
            ("SIZES", [("XSMALL", "1 credit/hr"), ("6XLARGE", "512 credits/hr")]),
            ("COMMANDS", [("CREATE WAREHOUSE", "New WH"), ("ALTER ... SET", "Resize")]),
            ("SCALING", [("Scale up", "Resize"), ("Scale out", "Multi-cluster")]),
            ("SAVING", [("AUTO_SUSPEND", "Pause idle"), ("AUTO_RESUME", "Wake on query")]),
        ],
        "next_up": "Micro-Partitions",
        "next_desc": "How Snowflake stores and prunes data for speed.",
    },
    {
        "num": "03", "phase": "Phase 1 · Foundations",
        "title": "Micro-\nPartitions",
        "description": "Snowflake automatically stores data in compressed, columnar micro-partitions (50–500 MB each). Metadata on every partition lets Snowflake skip irrelevant data — this is 'pruning', and it's why queries are fast.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Automatic — you never create or manage partitions",
            "Columnar + compressed = less storage, faster scans",
            "Metadata enables pruning — skip data that can't match",
            "Clustering keeps related data together for big tables",
        ],
        "types_title": "KEY IDEAS",
        "types": [
            ("📦", "Micro-partition", "50–500 MB compressed columnar unit"),
            ("✂️", "Pruning", "Skip partitions that can't match a filter"),
            ("🗂️", "Clustering", "How well-sorted data is across partitions"),
        ],
        "quote": "Snowflake reads less data, not faster data —\nthat's the secret to its speed.",
        "bp_boxes": ["Load", "Auto-\npartition", "Store\nmetadata", "Prune on\nquery"],
        "bp_note": "Min/max metadata per partition powers automatic pruning.",
        "at_a_glance": [
            ("📦", "SIZE", "50–500 MB"),
            ("🗜️", "FORMAT", "Columnar"),
            ("🤖", "MANAGED", "Automatic"),
        ],
        "real_world": [
            ("🔎", "Analytics", "Filter billions of rows, scan only a few partitions"),
            ("📅", "Time-series", "Date filters prune to relevant days instantly"),
            ("🏬", "Large tables", "Clustering keys keep TB-scale tables fast"),
            ("💸", "Cost", "Less scanned = fewer credits burned"),
        ],
        "did_you_know": [
            ("✂️", "Good pruning can skip 99% of a table for a selective query."),
            ("🔑", "Clustering keys only help on very large (>1TB) tables."),
            ("📊", "Each partition stores min, max, and count per column."),
        ],
        "how_title": "THE FLOW",
        "how": [
            ("📥", "INGEST", "Data split into\npartitions"),
            ("🏷️", "META", "Min/max stored\nper column"),
            ("✂️", "PRUNE", "Skip non-\nmatching data"),
        ],
        "ex_title": "PRUNING IN ACTION",
        "ex_cards": [
            ("🗃️", "1000 parts", "Full table"),
            ("🔍", "WHERE", "date=today"),
            ("✅", "3 parts", "Scanned"),
        ],
        "g1": [
            ("AUTOMATIC", ["Partitioning", "Compression", "Metadata", "Pruning"]),
            ("YOU CONTROL", ["Clustering keys", "Reclustering", "Table design"]),
        ],
        "g2": [
            ("GOOD FOR", [("✓", "Selective filters"), ("✓", "Date ranges"), ("✓", "Big tables")]),
            ("WATCH", [("!", "Over-clustering"), ("!", "Tiny tables"), ("!", "Cost of recluster")]),
        ],
        "footer": "Understanding pruning is how you write fast, cheap queries.",
        "quick_ref": [
            ("STORAGE", [("Columnar", "Per-column"), ("Compressed", "Auto")]),
            ("METADATA", [("Min/Max", "Per column"), ("Count", "Per partition")]),
            ("SPEED", [("Pruning", "Skip data"), ("Clustering", "Sort order")]),
            ("SCALE", [("Micro-part", "50–500MB"), (">1TB", "Add clustering")]),
        ],
        "next_up": "Loading Data",
        "next_desc": "Get data into Snowflake with COPY and Snowpipe.",
    },
    {
        "num": "04", "phase": "Phase 2 · Data Loading",
        "title": "Loading\nData",
        "description": "Get data in with stages + COPY INTO for bulk loads, or Snowpipe for continuous auto-loading. Snowflake handles CSV, JSON, Parquet, Avro and more — and parallelises loading automatically.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "COPY INTO bulk-loads files fast, in parallel",
            "Snowpipe auto-loads the moment files arrive — serverless",
            "Stages abstract where files live (S3, Azure, GCS, internal)",
            "Load structured AND semi-structured data the same way",
        ],
        "types_title": "TWO LOAD MODES",
        "types": [
            ("📦", "COPY INTO", "Bulk load — uses a warehouse"),
            ("🚰", "Snowpipe", "Continuous auto-load — serverless"),
            ("🗂️", "Stages", "Pointers to where your files live"),
        ],
        "quote": "Batch or streaming, structured or JSON —\nSnowflake loads it all the same way.",
        "bp_boxes": ["Files", "Stage", "COPY /\nSnowpipe", "Table"],
        "bp_note": "Snowpipe uses cloud notifications to load files automatically.",
        "at_a_glance": [
            ("📄", "FORMATS", "CSV, JSON, Parquet"),
            ("🚰", "CONTINUOUS", "Snowpipe"),
            ("⚡", "PARALLEL", "Automatic"),
        ],
        "real_world": [
            ("📱", "Apps", "Snowpipe streams event logs in near real-time"),
            ("🏭", "IoT", "Sensor files auto-load as they land"),
            ("📊", "BI", "Nightly COPY loads for dashboards"),
            ("🔗", "Kafka", "Snowflake Kafka connector streams topics"),
        ],
        "did_you_know": [
            ("🚰", "Snowpipe is serverless — no warehouse needed to load."),
            ("📦", "COPY INTO can skip bad rows with ON_ERROR=CONTINUE."),
            ("🔄", "You can VALIDATE a load before committing it."),
        ],
        "how_title": "LOADING STEPS",
        "how": [
            ("🗂️", "STAGE", "Point to your\nfiles"),
            ("📋", "FORMAT", "Define file\nformat"),
            ("📥", "COPY", "Load into\nthe table"),
        ],
        "ex_title": "STAGE TYPES",
        "ex_cards": [
            ("👤", "USER", "@~"),
            ("📋", "TABLE", "@%tbl"),
            ("☁️", "EXTERNAL", "S3/Azure"),
        ],
        "g1": [
            ("FORMATS", ["CSV", "JSON", "Parquet", "Avro / ORC"]),
            ("ON_ERROR", ["ABORT (default)", "CONTINUE", "SKIP_FILE"]),
        ],
        "g2": [
            ("BULK (COPY)", [("→", "Big batches"), ("→", "Uses warehouse"), ("→", "Manual/scheduled")]),
            ("STREAM (PIPE)", [("→", "Continuous"), ("→", "Serverless"), ("→", "Auto-ingest")]),
        ],
        "footer": "Loading well means clean, reliable data for everything downstream.",
        "quick_ref": [
            ("LOAD", [("COPY INTO", "Bulk"), ("Snowpipe", "Stream")]),
            ("STAGES", [("Internal", "@stage"), ("External", "S3/Azure")]),
            ("FORMATS", [("CSV", "Structured"), ("JSON", "VARIANT")]),
            ("ERRORS", [("CONTINUE", "Skip bad rows"), ("VALIDATION", "Dry run")]),
        ],
        "next_up": "Semi-Structured Data",
        "next_desc": "Query JSON as easily as tables with VARIANT.",
    },
    {
        "num": "05", "phase": "Phase 2 · Data Loading",
        "title": "Semi-\nStructured",
        "description": "Snowflake's VARIANT type stores JSON, Avro, and XML natively — no flattening needed up front. Query nested fields with path notation and explode arrays into rows with FLATTEN.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Store raw JSON without designing a schema first",
            "Query nested fields as fast as structured columns",
            "FLATTEN turns arrays into queryable rows",
            "Schema-on-read — adapt as your data evolves",
        ],
        "types_title": "KEY TOOLS",
        "types": [
            ("📦", "VARIANT", "Column type that holds any JSON"),
            ("🛣️", "Path notation", "col:field.subfield::type"),
            ("💥", "FLATTEN", "Explode arrays into rows"),
        ],
        "quote": "JSON isn't second-class in Snowflake —\nit queries just like a table.",
        "bp_boxes": ["JSON", "VARIANT\ncolumn", "Path /\nFLATTEN", "Rows"],
        "bp_note": "Access nested values with colon paths and :: casting.",
        "at_a_glance": [
            ("📦", "TYPE", "VARIANT"),
            ("📏", "MAX", "16 MB / row"),
            ("💥", "EXPLODE", "FLATTEN"),
        ],
        "real_world": [
            ("🛒", "E-commerce", "Store nested cart/order events as JSON"),
            ("📱", "Apps", "Event payloads land as VARIANT"),
            ("🌐", "APIs", "Raw API responses queried directly"),
            ("📡", "IoT", "Nested sensor readings without ETL"),
        ],
        "did_you_know": [
            ("📏", "A VARIANT value can hold up to 16 MB compressed."),
            ("⚡", "Snowflake auto-optimises frequently-queried JSON paths."),
            ("🔀", "FLATTEN is a table function used with LATERAL."),
        ],
        "how_title": "QUERYING JSON",
        "how": [
            ("📥", "LOAD", "JSON into a\nVARIANT column"),
            ("🛣️", "PATH", "Access nested\nfields"),
            ("💥", "FLATTEN", "Explode arrays\ninto rows"),
        ],
        "ex_title": "PATH SYNTAX",
        "ex_cards": [
            ("🔑", "FIELD", "v:name"),
            ("📐", "NESTED", "v:addr.city"),
            ("🎯", "CAST", "::STRING"),
        ],
        "g1": [
            ("FUNCTIONS", ["FLATTEN", "PARSE_JSON", "OBJECT_KEYS", "ARRAY_SIZE"]),
            ("CASTS", ["::STRING", "::NUMBER", "::BOOLEAN", "::TIMESTAMP"]),
        ],
        "g2": [
            ("STORE", [("✓", "No schema first"), ("✓", "Raw JSON"), ("✓", "Evolves freely")]),
            ("QUERY", [("→", "Path notation"), ("→", "FLATTEN arrays"), ("→", "Cast types")]),
        ],
        "footer": "Semi-structured mastery unlocks modern app & event data.",
        "quick_ref": [
            ("TYPE", [("VARIANT", "Any JSON"), ("OBJECT", "Key-value")]),
            ("ACCESS", [("col:path", "Navigate"), ("::type", "Cast")]),
            ("EXPLODE", [("FLATTEN", "Arrays→rows"), ("LATERAL", "Join")]),
            ("PARSE", [("PARSE_JSON", "String→JSON"), ("TO_JSON", "Back")]),
        ],
        "next_up": "SQL Transformations",
        "next_desc": "Window functions, QUALIFY, and Snowflake SQL gems.",
    },
    {
        "num": "06", "phase": "Phase 3 · Transformations",
        "title": "SQL\nPower",
        "description": "Snowflake SQL includes powerful extras: window functions with QUALIFY, PIVOT/UNPIVOT, approximate functions for speed, and LATERAL joins — everything you need to transform data at scale.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "QUALIFY filters window results without a subquery",
            "Approximate functions give instant answers on huge data",
            "PIVOT/UNPIVOT reshape data in one statement",
            "It's ANSI SQL plus — familiar but more powerful",
        ],
        "types_title": "SIGNATURE FEATURES",
        "types": [
            ("🪟", "QUALIFY", "Filter window functions inline"),
            ("📊", "PIVOT", "Rows to columns and back"),
            ("⚡", "APPROX_*", "Fast estimates on big data"),
        ],
        "quote": "QUALIFY is the one-line trick that\nreplaces messy nested subqueries.",
        "bp_boxes": ["Raw", "Window /\nAggregate", "QUALIFY\nfilter", "Result"],
        "bp_note": "QUALIFY is to window functions what HAVING is to GROUP BY.",
        "at_a_glance": [
            ("🪟", "WINDOWS", "+ QUALIFY"),
            ("⚡", "SPEED", "APPROX funcs"),
            ("📐", "RESHAPE", "PIVOT"),
        ],
        "real_world": [
            ("🏆", "Ranking", "Top-N per group in one clean query"),
            ("📈", "Analytics", "Running totals & moving averages"),
            ("🔢", "Big data", "APPROX_COUNT_DISTINCT on billions of rows"),
            ("📋", "Reports", "PIVOT monthly data into columns"),
        ],
        "did_you_know": [
            ("⚡", "APPROX_COUNT_DISTINCT uses HyperLogLog — fast & tiny."),
            ("🪟", "QUALIFY is a Snowflake extension not in standard SQL."),
            ("🎲", "SAMPLE lets you query a random % of a table instantly."),
        ],
        "how_title": "TRANSFORM FLOW",
        "how": [
            ("🪟", "WINDOW", "Rank / aggregate\nover partitions"),
            ("🔎", "QUALIFY", "Filter the\nwindow output"),
            ("📤", "OUTPUT", "Clean, shaped\nresult"),
        ],
        "ex_title": "TOP-3 PER GROUP",
        "ex_cards": [
            ("🔢", "ROW_NUMBER", "OVER..."),
            ("🎯", "QUALIFY", "rn <= 3"),
            ("✅", "RESULT", "Top 3 each"),
        ],
        "g1": [
            ("WINDOW FN", ["ROW_NUMBER", "RANK", "LAG / LEAD", "SUM OVER"]),
            ("RESHAPE", ["PIVOT", "UNPIVOT", "LATERAL", "FLATTEN"]),
        ],
        "g2": [
            ("APPROX", [("→", "COUNT_DISTINCT"), ("→", "PERCENTILE"), ("→", "TOP_K")]),
            ("CONDITIONAL", [("→", "IFF"), ("→", "DECODE"), ("→", "CASE")]),
        ],
        "footer": "Great SQL is the core skill every data engineer is hired for.",
        "quick_ref": [
            ("WINDOWS", [("OVER()", "Partition"), ("QUALIFY", "Filter")]),
            ("RESHAPE", [("PIVOT", "Rows→cols"), ("UNPIVOT", "Cols→rows")]),
            ("FAST", [("APPROX_*", "Estimates"), ("SAMPLE", "Random %")]),
            ("LOGIC", [("IFF", "Ternary"), ("CASE", "Multi-branch")]),
        ],
        "next_up": "Time Travel",
        "next_desc": "Query and restore data from the past.",
    },
    {
        "num": "07", "phase": "Phase 3 · Transformations",
        "title": "Time\nTravel",
        "description": "Time Travel lets you query data as it existed in the past — up to 90 days on Enterprise. Recover from bad updates, deletes, or drops instantly with AT/BEFORE and UNDROP. Fail-safe adds 7 more days of Snowflake-managed recovery.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Query data as it was seconds, hours, or days ago",
            "UNDROP a table, schema, or database you deleted by mistake",
            "Recover from a bad UPDATE without a backup",
            "Fail-safe adds 7 days of last-resort recovery",
        ],
        "types_title": "RECOVERY TOOLS",
        "types": [
            ("⏰", "Time Travel", "Query/restore up to 90 days back"),
            ("↩️", "UNDROP", "Instantly restore dropped objects"),
            ("🛟", "Fail-safe", "7-day Snowflake-managed safety net"),
        ],
        "quote": "The best backup is the one you never\nhad to set up — that's Time Travel.",
        "bp_boxes": ["Mistake", "AT /\nBEFORE", "Recover\ndata", "Restored"],
        "bp_note": "Fail-safe is support-only and starts after Time Travel expires.",
        "at_a_glance": [
            ("⏰", "MAX", "90 days"),
            ("🔧", "DEFAULT", "1 day"),
            ("🛟", "FAIL-SAFE", "7 days"),
        ],
        "real_world": [
            ("🚨", "Oops", "Recover a table dropped by accident"),
            ("🔍", "Audit", "See exactly what data looked like last week"),
            ("🧪", "Testing", "Clone a point-in-time state for QA"),
            ("💾", "DR", "Restore after a bad ETL run"),
        ],
        "did_you_know": [
            ("🛟", "Fail-safe can't be queried — only Snowflake support recovers it."),
            ("⏰", "90-day Time Travel needs Enterprise edition; default is 1 day."),
            ("↩️", "UNDROP works on tables, schemas, AND whole databases."),
        ],
        "how_title": "RECOVERY FLOW",
        "how": [
            ("⏰", "CHOOSE", "Pick a past\ntimestamp"),
            ("🔎", "QUERY", "AT() or\nBEFORE()"),
            ("↩️", "RESTORE", "Recreate or\nUNDROP"),
        ],
        "ex_title": "RECOVERY WAYS",
        "ex_cards": [
            ("🕐", "OFFSET", "-3600s"),
            ("📌", "STATEMENT", "before id"),
            ("↩️", "UNDROP", "TABLE t"),
        ],
        "g1": [
            ("SYNTAX", ["AT(OFFSET=>-n)", "AT(TIMESTAMP=>..)", "BEFORE(STATEMENT=>..)", "UNDROP"]),
            ("RETENTION", ["Standard: 1 day", "Enterprise: 90", "Transient: 0–1"]),
        ],
        "g2": [
            ("TIME TRAVEL", [("✓", "You query it"), ("✓", "Up to 90 days"), ("✓", "Configurable")]),
            ("FAIL-SAFE", [("!", "Support only"), ("!", "7 days fixed"), ("!", "Not queryable")]),
        ],
        "footer": "Time Travel turns 'we lost data' into 'one query fixes it'.",
        "quick_ref": [
            ("QUERY PAST", [("AT(OFFSET)", "Seconds ago"), ("BEFORE(STMT)", "Pre-query")]),
            ("RESTORE", [("UNDROP", "Bring back"), ("CLONE AT", "Point-in-time")]),
            ("LIMITS", [("Default", "1 day"), ("Max", "90 days")]),
            ("SAFETY", [("Fail-safe", "7 days"), ("Support", "Only")]),
        ],
        "next_up": "Zero-Copy Cloning",
        "next_desc": "Instant dev/test copies with no storage cost.",
    },
    {
        "num": "08", "phase": "Phase 3 · Transformations",
        "title": "Zero-Copy\nCloning",
        "description": "CREATE ... CLONE makes an instant, writable copy of a table, schema, or entire database — with no storage cost until the clone changes. Perfect for dev, test, and experimentation environments.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Clone a whole database in seconds, not hours",
            "Zero storage cost until the clone diverges",
            "Give every developer a full-data sandbox instantly",
            "Combine with Time Travel to clone a past state",
        ],
        "types_title": "WHAT YOU CAN CLONE",
        "types": [
            ("📄", "Table", "A single table's data & structure"),
            ("🗂️", "Schema", "All objects in a schema"),
            ("🗄️", "Database", "An entire database instantly"),
        ],
        "quote": "Why copy terabytes when you can clone\nthem in seconds for free?",
        "bp_boxes": ["Prod DB", "CLONE", "Instant\ncopy", "Dev / Test"],
        "bp_note": "Only changed data consumes storage — the rest is shared.",
        "at_a_glance": [
            ("⚡", "SPEED", "Seconds"),
            ("💰", "COST", "₹0 until changed"),
            ("📐", "SCOPE", "Table→Database"),
        ],
        "real_world": [
            ("🧑‍💻", "Dev", "Per-developer sandbox with full prod data"),
            ("🧪", "QA", "Fresh test env for every release"),
            ("📊", "Analytics", "Experiment without touching production"),
            ("🎓", "Training", "Give learners real data safely"),
        ],
        "did_you_know": [
            ("💰", "A clone costs nothing until you modify its data."),
            ("⏰", "You can clone a table AS IT WAS via Time Travel."),
            ("🔄", "Clones are fully independent — write freely."),
        ],
        "how_title": "CLONING FLOW",
        "how": [
            ("🎯", "PICK", "Choose what\nto clone"),
            ("🧬", "CLONE", "CREATE ...\nCLONE"),
            ("✍️", "USE", "Write freely,\nno impact"),
        ],
        "ex_title": "CLONE TARGETS",
        "ex_cards": [
            ("📄", "TABLE", "CLONE t"),
            ("🗂️", "SCHEMA", "CLONE s"),
            ("🗄️", "DATABASE", "CLONE db"),
        ],
        "g1": [
            ("SYNTAX", ["CREATE TABLE .. CLONE", "CREATE SCHEMA .. CLONE", "CREATE DATABASE .. CLONE", "+ AT/BEFORE"]),
            ("USE CASES", ["Dev sandboxes", "QA environments", "Experiments"]),
        ],
        "g2": [
            ("BENEFITS", [("✓", "Instant"), ("✓", "No storage cost"), ("✓", "Independent")]),
            ("PAIR WITH", [("→", "Time Travel"), ("→", "CI/CD"), ("→", "Data sharing")]),
        ],
        "footer": "Zero-copy cloning is the feature that makes every team faster.",
        "quick_ref": [
            ("CLONE", [("TABLE", "One table"), ("DATABASE", "Everything")]),
            ("COST", [("Create", "Free"), ("Diverge", "Pay changes")]),
            ("TIME", [("CLONE AT", "Past state"), ("BEFORE", "Pre-query")]),
            ("USE", [("Dev", "Sandbox"), ("QA", "Test env")]),
        ],
        "next_up": "Snowpark",
        "next_desc": "Run Python inside Snowflake — no data movement.",
    },
    {
        "num": "09", "phase": "Phase 4 · Engineering",
        "title": "Snowpark\n& Python",
        "description": "Snowpark lets you write Python, Java, or Scala that runs inside Snowflake. Use a pandas-like DataFrame API, deploy UDFs and stored procedures, and even train ML models where your data lives — zero data movement.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Write Python that runs on Snowflake compute",
            "DataFrame API feels like pandas but scales massively",
            "Deploy UDFs so ML predictions run inside SQL",
            "No data egress — process where the data lives",
        ],
        "types_title": "WHAT YOU BUILD",
        "types": [
            ("🐼", "DataFrames", "pandas-like API on Snowflake compute"),
            ("🧩", "UDFs", "Python functions callable from SQL"),
            ("⚙️", "Procedures", "Full procedural logic in Python"),
        ],
        "quote": "Bring your code to the data —\nnot the data to your code.",
        "bp_boxes": ["Python", "Snowpark\nDataFrame", "Runs in\nSnowflake", "Results"],
        "bp_note": "Snowpark pushes computation down to Snowflake's engine.",
        "at_a_glance": [
            ("🐍", "LANGS", "Python, Java, Scala"),
            ("🐼", "API", "DataFrame"),
            ("🚫", "EGRESS", "None"),
        ],
        "real_world": [
            ("🤖", "ML", "Train & serve models inside Snowflake"),
            ("🔧", "ETL", "Complex transforms in Python"),
            ("📊", "Features", "Feature engineering at scale"),
            ("🧮", "UDFs", "Custom logic callable from any query"),
        ],
        "did_you_know": [
            ("🚫", "Data never leaves Snowflake — great for security & compliance."),
            ("🐼", "The Snowpark DataFrame API mirrors pandas closely."),
            ("🧩", "A Python UDF turns ML inference into a SQL function."),
        ],
        "how_title": "SNOWPARK FLOW",
        "how": [
            ("🔌", "CONNECT", "Create a\nsession"),
            ("🐼", "TRANSFORM", "DataFrame\noperations"),
            ("🚀", "DEPLOY", "UDFs /\nprocedures"),
        ],
        "ex_title": "DATAFRAME OPS",
        "ex_cards": [
            ("🔍", "FILTER", ".filter()"),
            ("📊", "GROUP", ".group_by()"),
            ("💾", "SAVE", ".save_as_table()"),
        ],
        "g1": [
            ("LANGUAGES", ["Python", "Java", "Scala", "SQL interop"]),
            ("DEPLOY", ["UDFs", "UDTFs", "Stored procs", "ML models"]),
        ],
        "g2": [
            ("DATAFRAME", [("→", "filter"), ("→", "group_by"), ("→", "join")]),
            ("BENEFITS", [("✓", "No egress"), ("✓", "Scales"), ("✓", "Familiar")]),
        ],
        "footer": "Snowpark is where data engineering meets data science.",
        "quick_ref": [
            ("API", [("Session", "Connect"), ("DataFrame", "Transform")]),
            ("DEPLOY", [("UDF", "SQL callable"), ("Procedure", "Logic")]),
            ("LANGS", [("Python", "Most common"), ("Java/Scala", "Also")]),
            ("WIN", [("No egress", "Secure"), ("Push-down", "Fast")]),
        ],
        "next_up": "Streams & Tasks",
        "next_desc": "Build real-time pipelines inside Snowflake.",
    },
    {
        "num": "10", "phase": "Phase 4 · Engineering",
        "title": "Streams\n& Tasks",
        "description": "Streams track changes (inserts, updates, deletes) on a table — Snowflake-native CDC. Tasks run SQL on a schedule or in a chain. Together they build real-time ELT pipelines with no external orchestrator.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Streams capture row-level changes automatically (CDC)",
            "Tasks schedule or chain SQL — a pipeline DAG",
            "Combine for near-real-time ELT, no external tools",
            "Trigger tasks only when a stream has new data",
        ],
        "types_title": "THE BUILDING BLOCKS",
        "types": [
            ("🌊", "Stream", "Tracks changes on a table (CDC)"),
            ("⏱️", "Task", "Scheduled or chained SQL execution"),
            ("🔗", "Task DAG", "Chain tasks into a pipeline"),
        ],
        "quote": "Streams + Tasks = a real-time data\npipeline without leaving Snowflake.",
        "bp_boxes": ["Change", "Stream\ncaptures", "Task\nprocesses", "Target"],
        "bp_note": "Tasks can check SYSTEM$STREAM_HAS_DATA to run only when needed.",
        "at_a_glance": [
            ("🌊", "STREAM", "Row-level CDC"),
            ("⏱️", "TASK", "Scheduled SQL"),
            ("🔗", "CHAIN", "Task DAGs"),
        ],
        "real_world": [
            ("💳", "Fintech", "Process new transactions every minute"),
            ("📦", "Retail", "Update inventory as orders stream in"),
            ("📱", "Apps", "Aggregate events in near real-time"),
            ("🔄", "ELT", "Raw → clean → mart, fully automated"),
        ],
        "did_you_know": [
            ("🌊", "A stream stores only the CHANGES, not a full copy."),
            ("⏱️", "Tasks can run as often as every minute — or serverless."),
            ("🔗", "Chained tasks form a DAG — a whole pipeline in Snowflake."),
        ],
        "how_title": "PIPELINE FLOW",
        "how": [
            ("🌊", "TRACK", "Stream on\nthe table"),
            ("⏱️", "SCHEDULE", "Task runs\nSQL"),
            ("🔗", "CHAIN", "More tasks\nafter"),
        ],
        "ex_title": "PIPELINE STAGES",
        "ex_cards": [
            ("📥", "RAW", "New rows"),
            ("🧹", "CLEAN", "Task 1"),
            ("📊", "AGG", "Task 2"),
        ],
        "g1": [
            ("STREAMS", ["Standard", "Append-only", "Insert-only", "SYSTEM$STREAM_HAS_DATA"]),
            ("TASKS", ["SCHEDULE", "AFTER (chain)", "WHEN condition", "Serverless"]),
        ],
        "g2": [
            ("STREAM", [("→", "Tracks CDC"), ("→", "Insert/upd/del"), ("→", "Consumed once")]),
            ("TASK", [("→", "Runs SQL"), ("→", "Scheduled"), ("→", "Chainable")]),
        ],
        "footer": "This is how modern real-time data platforms are built.",
        "quick_ref": [
            ("STREAM", [("CREATE STREAM", "On table"), ("CDC", "Track changes")]),
            ("TASK", [("SCHEDULE", "Cron/interval"), ("AFTER", "Chain")]),
            ("TRIGGER", [("STREAM_HAS_DATA", "Run if new"), ("WHEN", "Condition")]),
            ("PATTERN", [("Raw→Clean", "Task 1"), ("Clean→Mart", "Task 2")]),
        ],
        "next_up": "Security & RBAC",
        "next_desc": "Roles, masking, and enterprise governance.",
    },
    {
        "num": "11", "phase": "Phase 5 · Governance",
        "title": "Security\n& RBAC",
        "description": "Snowflake secures data with Role-Based Access Control, dynamic data masking, row-level security, and always-on encryption. Grant privileges to roles, roles to users — least-privilege by design.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "RBAC — grant privileges to roles, roles to users",
            "Dynamic masking hides PII from unauthorised roles",
            "Row-level security filters rows per user",
            "Encryption at rest & in transit is always on",
        ],
        "types_title": "SECURITY LAYERS",
        "types": [
            ("👥", "RBAC", "Role-based access control hierarchy"),
            ("🎭", "Masking", "Hide sensitive columns dynamically"),
            ("🔐", "Encryption", "AES-256, automatic, always on"),
        ],
        "quote": "Least privilege isn't paranoia —\nit's professional data governance.",
        "bp_boxes": ["Privilege", "Role", "User", "Access"],
        "bp_note": "ACCOUNTADMIN sits on top; build custom roles under SYSADMIN.",
        "at_a_glance": [
            ("👥", "MODEL", "RBAC + DAC"),
            ("🔐", "ENCRYPT", "AES-256"),
            ("🎭", "MASK", "Dynamic"),
        ],
        "real_world": [
            ("🏦", "Banking", "Mask account numbers from analysts"),
            ("🏥", "Healthcare", "Row-level access to patient data"),
            ("🌍", "Global", "Region-restricted data via policies"),
            ("🇮🇳", "India", "DPDP-compliant PAN/Aadhaar masking"),
        ],
        "did_you_know": [
            ("🔐", "Encryption is automatic — keys rotate every 30 days."),
            ("🎭", "One masking policy can protect a column across all queries."),
            ("👑", "Best practice: never use ACCOUNTADMIN for daily work."),
        ],
        "how_title": "GOVERNANCE FLOW",
        "how": [
            ("👥", "ROLES", "Create role\nhierarchy"),
            ("🔑", "GRANT", "Privileges to\nroles"),
            ("🎭", "PROTECT", "Masking &\nrow policies"),
        ],
        "ex_title": "ROLE HIERARCHY",
        "ex_cards": [
            ("👑", "ACCOUNTADMIN", "Top"),
            ("🛠️", "SYSADMIN", "Objects"),
            ("👤", "PUBLIC", "All users"),
        ],
        "g1": [
            ("SYSTEM ROLES", ["ACCOUNTADMIN", "SECURITYADMIN", "SYSADMIN", "PUBLIC"]),
            ("PROTECTION", ["Masking policy", "Row access policy", "Object tags"]),
        ],
        "g2": [
            ("RBAC", [("→", "Grant to roles"), ("→", "Roles to users"), ("→", "Inheritance")]),
            ("SECURE", [("✓", "Masking"), ("✓", "Row-level"), ("✓", "Encryption")]),
        ],
        "footer": "Governance skills are what enterprises pay senior engineers for.",
        "quick_ref": [
            ("ROLES", [("System", "Built-in"), ("Custom", "Under SYSADMIN")]),
            ("MASK", [("Policy", "Per column"), ("Dynamic", "By role")]),
            ("ROW", [("Row policy", "Filter rows"), ("Per user", "Context")]),
            ("CRYPTO", [("At rest", "AES-256"), ("In transit", "TLS")]),
        ],
        "next_up": "Cost & Certification",
        "next_desc": "Optimise spend and pass SnowPro Core.",
    },
    {
        "num": "12", "phase": "Phase 5 · Governance",
        "title": "Cost &\nSnowPro",
        "description": "Run Snowflake efficiently with resource monitors, right-sized warehouses, and query tuning — then prove your skills with the SnowPro Core certification. This is the skill combo that lands ₹18–45 LPA data roles.",
        "why_title": "WHY IT MATTERS",
        "why": [
            "Resource monitors cap spend before it surprises you",
            "Right-sizing warehouses is the #1 cost lever",
            "ACCOUNT_USAGE reveals your most expensive queries",
            "SnowPro Core certification proves it all to employers",
        ],
        "types_title": "THE FINAL SKILLS",
        "types": [
            ("💰", "Cost control", "Monitors, sizing, query tuning"),
            ("📊", "Monitoring", "ACCOUNT_USAGE views"),
            ("🏆", "SnowPro", "Industry-recognised certification"),
        ],
        "quote": "Running Snowflake cheaply is the skill\nthat gets data engineers promoted.",
        "bp_boxes": ["Monitor", "Optimise", "Certify", "Get hired"],
        "bp_note": "SnowPro Core validates all 6 exam domains you've now learned.",
        "at_a_glance": [
            ("💰", "CONTROL", "Resource monitors"),
            ("🏆", "CERT", "SnowPro Core"),
            ("💼", "SALARY", "₹18–45 LPA"),
        ],
        "real_world": [
            ("💸", "FinOps", "Cap monthly credits with monitors"),
            ("🔍", "Tuning", "Find & fix expensive queries"),
            ("🏆", "Careers", "SnowPro-certified engineers in demand"),
            ("📈", "Growth", "Cert + projects = job offers"),
        ],
        "did_you_know": [
            ("💰", "A resource monitor can auto-suspend at a credit limit."),
            ("🏆", "SnowPro Core is valid for 2 years and costs $175."),
            ("📊", "ACCOUNT_USAGE keeps up to 365 days of history."),
        ],
        "how_title": "YOUR PATH",
        "how": [
            ("💰", "OPTIMISE", "Monitors &\nsizing"),
            ("📚", "STUDY", "6 exam\ndomains"),
            ("🏆", "CERTIFY", "Pass SnowPro\nCore"),
        ],
        "ex_title": "EXAM DOMAINS",
        "ex_cards": [
            ("🏗️", "ARCH", "24%"),
            ("🔄", "TRANSFORM", "22%"),
            ("🔐", "SECURITY", "18%"),
        ],
        "g1": [
            ("COST TOOLS", ["Resource monitors", "Auto-suspend", "Right-sizing", "Query profile"]),
            ("MONITORING", ["ACCOUNT_USAGE", "QUERY_HISTORY", "METERING_HISTORY"]),
        ],
        "g2": [
            ("SAVE", [("→", "Suspend idle"), ("→", "Right-size"), ("→", "Cap credits")]),
            ("CERTIFY", [("→", "60+ practice Qs"), ("→", "Mock exams"), ("→", "Pass!")]),
        ],
        "footer": "You now know Snowflake end to end — go get certified & hired!",
        "quick_ref": [
            ("COST", [("Monitor", "Cap spend"), ("Right-size", "Save credits")]),
            ("WATCH", [("QUERY_HISTORY", "Slow queries"), ("METERING", "Credits")]),
            ("EXAM", [("SnowPro Core", "$175"), ("Valid", "2 years")]),
            ("NEXT", [("Advanced", "Data Engineer"), ("Career", "₹18–45 LPA")]),
        ],
        "next_up": "You Did It!",
        "next_desc": "Enrol at pjsacademy.com to go from here to certified.",
    },
]
